### ISSUE TITLE
看看这个 加进去吧

### ISSUE THREAD

**Issue by yitd** [Daiyimo/Access-chatGPT-in-Siri#1]
可以不用key
https://www.icloud.com/shortcuts/c005ea38f9af491986109f8ecf2bdc25

**Comment by Daiyimo** [comment]
可以是可以，但是暂不支持连续对话，单词对话会自动结束。而且调用的是第三方的网址，没有从域名openai里调取api。也就意味着数据不是直接到openai解析，安全性无法保证。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Daiyimo/Access-chatGPT-in-Siri"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 下午4:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1)





 
可以不用key
 https://www.icloud.com/shortcuts/c005ea38f9af491986109f8ecf2bdc25

**Comment by yitd** [comment]
> 

用官方的用户就必须有key才能用了，连续对话加上了
https://www.icloud.com/shortcuts/6806556a52a34045ab66eee87d114781

**Comment by Daiyimo** [comment]
你先测试一个问答有没有连续性，例如：给我五个数字.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Daiyimo/Access-chatGPT-in-Siri"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1)





   
用官方的用户就必须有key才能用了，连续对话加上了
 https://www.icloud.com/shortcuts/6806556a52a34045ab66eee87d114781

**Comment by Daiyimo** [comment]
你先测试一个问答有没有连续性，
例如：
给我五个数字.
其中最大的是哪个


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Daiyimo/Access-chatGPT-in-Siri"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1)





   
用官方的用户就必须有key才能用了，连续对话加上了
 https://www.icloud.com/shortcuts/6806556a52a34045ab66eee87d114781

**Comment by yitd** [comment]
看了你们的代码我悟了，现在ok了
https://www.icloud.com/shortcuts/31340d376cd5402686f7d62c2affbeaa

**Comment by yitd** [comment]
> 你先测试一个问答有没有连续性， 例如： 给我五个数字. 其中最大的是哪个
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Daiyimo/Access-chatGPT-in-Siri" ***@***.***&gt;; 发送时间:&nbsp;2023年2月12日(星期天) 下午5:10 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) 用官方的用户就必须有key才能用了，连续对话加上了 https://www.icloud.com/shortcuts/6806556a52a34045ab66eee87d114781 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

ok了
https://www.icloud.com/shortcuts/3619e1fe2f6a4fd0a421e102ab311818

**Comment by yitd** [comment]
> 你先测试一个问答有没有连续性， 例如： 给我五个数字. 其中最大的是哪个
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Daiyimo/Access-chatGPT-in-Siri" ***@***.***&gt;; 发送时间:&nbsp;2023年2月12日(星期天) 下午5:10 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) 用官方的用户就必须有key才能用了，连续对话加上了 https://www.icloud.com/shortcuts/6806556a52a34045ab66eee87d114781 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

发现一些问题，已修复，现在应该已经差不多了
https://www.icloud.com/shortcuts/e7ebe0eca80b46a9a32778b6517ea4c5

**Comment by yitd** [comment]
> 你先测试一个问答有没有连续性， 例如： 给我五个数字. 其中最大的是哪个
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Daiyimo/Access-chatGPT-in-Siri" ***@***.***&gt;; 发送时间:&nbsp;2023年2月12日(星期天) 下午5:10 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) 用官方的用户就必须有key才能用了，连续对话加上了 https://www.icloud.com/shortcuts/6806556a52a34045ab66eee87d114781 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

看了吗？加到readme里面呗，卖账号能盈利了，放心不会侵犯用户隐私。
https://www.icloud.com/shortcuts/2fb80b826a974468b50bfd883bc1d87a

**Comment by Daiyimo** [comment]
这样吧，我现在正在联系gitee的管理员，让他们给我开个国内的镜像主页。我把GitHub的项目仓库直接同步过去，把你的网址写到readme里。一方面是没有魔法的用户会首选去gitee看教程，可以给你引流，另一方面能进GitHub的也都有魔法需求量不是很大。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月13日(星期一) 晚上7:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1)





  
你先测试一个问答有没有连续性， 例如： 给我五个数字. 其中最大的是哪个
 …
 ------------------ 原始邮件 ------------------ 发件人: "Daiyimo/Access-chatGPT-in-Siri" @.&gt;; 发送时间:&nbsp;2023年2月12日(星期天) 下午5:10 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) 用官方的用户就必须有key才能用了，连续对话加上了 https://www.icloud.com/shortcuts/6806556a52a34045ab66eee87d114781 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
看了吗？加到readme里面呗，卖账号能盈利了，放心不会侵犯用户隐私。
 https://www.icloud.com/shortcuts/2fb80b826a974468b50bfd883bc1d87a

**Comment by yitd** [comment]
> 

emmm好，多谢了

**Comment by yitd** [comment]
更新了下，删除了没用的表单，提高了速度
https://www.icloud.com/shortcuts/4d4bf8ee55824e4680dcc541d490d7d3
以后最新版都更新在这个链接：https://aichatgpt.me/up

**Comment by Daiyimo** [comment]
gitee没通过。。。我可以把你的网站写到GitHub以及公告里作为一个免费接口使用，给我个网站吧。记得帮我推广GitHub项目



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月13日(星期一) 晚上7:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1)





   
emmm好，多谢了

**Comment by yitd** [comment]
> gitee没通过。。。我可以把你的网站写到GitHub以及公告里作为一个免费接口使用，给我个网站吧。记得帮我推广GitHub项目
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月13日(星期一) 晚上7:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) emmm好，多谢了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

https://aichatgpt.me/

**Comment by Daiyimo** [comment]
那个格物时间是你吗？是的话我直接在评论区给你引流过去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 中午12:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1)





  
gitee没通过。。。我可以把你的网站写到GitHub以及公告里作为一个免费接口使用，给我个网站吧。记得帮我推广GitHub项目
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年2月13日(星期一) 晚上7:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) emmm好，多谢了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
https://aichatgpt.me/

**Comment by yitd** [comment]
> 那个格物时间是你吗？是的话我直接在评论区给你引流过去
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月14日(星期二) 中午12:14 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) gitee没通过。。。我可以把你的网站写到GitHub以及公告里作为一个免费接口使用，给我个网站吧。记得帮我推广GitHub项目 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年2月13日(星期一) 晚上7:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) emmm好，多谢了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; https://aichatgpt.me/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不是我，多谢你，已经把你项目写在网页底部了 https://aichatgpt.me/Siri.html

**Comment by yitd** [comment]
> 那个格物时间是你吗？是的话我直接在评论区给你引流过去
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月14日(星期二) 中午12:14 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) gitee没通过。。。我可以把你的网站写到GitHub以及公告里作为一个免费接口使用，给我个网站吧。记得帮我推广GitHub项目 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年2月13日(星期一) 晚上7:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Daiyimo/Access-chatGPT-in-Siri] 看看这个 加进去吧 (Issue #1) emmm好，多谢了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; https://aichatgpt.me/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

放在底部不够意思^_^ 放上来了
