### ISSUE TITLE
ai对话是空白

### ISSUE THREAD

**Issue by akeboshi1** [Daiyimo/Access-chatGPT-in-Siri#12]
已注册openai的账号，apikey一切都正常，但ai对话是空白的
如下图：
![image](https://user-images.githubusercontent.com/18412751/219302855-0f7252f3-fdb5-40b3-9f15-a306ae432a6c.png)
机型：iphone 11 
ios版本： 16.0

**Comment by marslhx** [comment]
me 2

**Comment by Daiyimo** [comment]
尝试新的版本，已修复

**Comment by akeboshi1** [comment]
新版本地址在哪里？

**Comment by hayleeXinyi** [comment]
我的也是。

**Comment by fastfading** [comment]
一样的，  尝试了好些版本， 都是这样，  这个是不是骗key的程序

**Comment by akeboshi1** [comment]
对作者还是表示感谢，但由于不太好用，为了防止自己的key被滥用，我已经更新了key，且已删除该脚本应用
