### ISSUE TITLE
API key 调用额度咨询

### ISSUE THREAD

**Issue by peihaojie** [Daiyimo/Access-chatGPT-in-Siri#7]
您好，请问 key 的调用有上限吗？是超过某个阈值就要开始收费还是可以一直免费使用？

**Comment by Linkegee** [comment]
早期注册账号内都有18刀额度用来给API消耗的。具体明细去官网看API接口说明文档。

**Comment by Linkegee** [comment]
> 您好，请问 key 的调用有上限吗？是超过某个阈值就要开始收费还是可以一直免费使用？


早期注册账号内都有18刀额度用来给API消耗的。具体明细去官网看API接口说明文档。

**Comment by peihaojie** [comment]
> > 您好，请问 key 的调用有上限吗？是超过某个阈值就要开始收费还是可以一直免费使用？
> 
> 
> 
> 
> 
> 早期注册账号内都有18刀额度用来给API消耗的。具体明细去官网看API接口说明文档。
> 
> 
> 
> 
嗷嗷 好的 非常感谢🙏
